name: Java CI

on: [push]

jobs:
  osx:
    runs-on: macos
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.0'
          java-package: jdk
          architecture: x64

      - name: Create .dmg
        run: ./gradlew jpackage --stacktrace

      - name: Upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: macOS dmg
          path: build/image/remembrance-agent-desktop-2.0.0.dmg

  windows:

    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.0'
          java-package: jdk
          architecture: x64

      - name: Create .exe
        run: ./gradlew jpackage --stacktrace

      - name: Upload installer
        uses: actions/upload-artifact@v1
        with:
          name: Windows exe
          path: build/image/remembrance-agent-desktop-2.0.0.exe
