name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: zulu@14.27.1

    - name: Print javac version
      run: echo $(javac --version)

    - name: Set Java Home
      run: export JAVA_HOME=$(dirname $(dirname $(which javac))) && echo ${JAVA_HOME}

    - name: Build
      run: sudo VERSION=2.0.0 ./gradlew jpackage --stacktrace
