name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Bash for GitHub Actions
      uses: jcblw/bash@1.0.0
      args: VERSION=2.0.0 ./bin/build
