name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - name: Download JDK 14
      run: curl -O "https://static.azul.com/zulu/bin/zulu14.27.1-ca-jdk14-linux_musl_x64.tar.gz"

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 14
        jdkFile: zulu14.27.1-ca-jdk14-linux_musl_x64.tar.gz

    - name: Add gradle.properties
      run: echo "org.gradle.java.home=$(dirname $(dirname $(which javac)))" > gradle.properties && cat gradle.properties

    - name: Build
      run: sudo VERSION=2.0.0 ./gradlew jpackage --stacktrace
