name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.0
        java-package: jdk
        architecture: x64

    - name: Print javac version
      run: echo $(javac --version)

    - name: Build
      run: sudo JAVA_HOME=$(dirname $(dirname $(which javac))) VERSION=2.0.0 ./gradlew jpackage --stacktrace
