name: Java CI

on: [push]

jobs:
  macOS:
    runs-on: macos

    env:
      VERSION: $(cat VERSION)

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.0'
          java-package: jdk
          architecture: x64

      - name: Create .dmg
        run: ./gradlew jpackage --stacktrace

      - name: Upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: remembrance-agent-desktop-v${{ env.VERSION }}-macos-dmg
          path: build/image/remembrance-agent-desktop-v${{ env.VERSION }}.dmg

  Windows:
    runs-on: [windows-latest]

    env:
      VERSION: $(cat VERSION)

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.0'
          java-package: jdk
          architecture: x64

      - name: Create .msi
        run: ./gradlew jpackage --stacktrace

      - name: Upload installer
        uses: actions/upload-artifact@v1
        with:
          name: remembrance-agent-desktop-desktop-v${{ env.VERSION }}-windows-msi
          path: build/image/remembrance-agent-desktop-v${{ env.VERSION }}.msi
